# Generated by Django 4.0.6 on 2022-07-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blogs',
        ),
    ]
